# AI Provider Interface Contract
# Feature 002: Advanced Terminal Productivity Suite

openapi: 3.0.3
info:
  title: AI Provider Interface
  description: |
    Interface contract for AI provider integration in the Advanced Terminal Productivity Suite.
    Supports both CLI-based and API-based authentication methods.
  version: 1.0.0
  contact:
    name: Advanced Terminal Productivity
    url: https://github.com/ghostty-config-files

servers:
  - url: cli://local
    description: CLI-based authentication (preferred)
  - url: https://api.openai.com/v1
    description: OpenAI API endpoint
  - url: https://api.anthropic.com/v1
    description: Anthropic Claude API endpoint
  - url: https://generativelanguage.googleapis.com/v1beta
    description: Google Gemini API endpoint

paths:
  /command-suggestion:
    post:
      summary: Get AI-powered command suggestion
      description: |
        Request a command suggestion based on user query and context.
        Supports both CLI and API modes.
      operationId: getCommandSuggestion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommandSuggestionRequest'
      responses:
        '200':
          description: Command suggestion generated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommandSuggestionResponse'
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Authentication failed
        '429':
          description: Rate limit exceeded
        '500':
          description: Internal server error

  /provider-status:
    get:
      summary: Check provider availability
      description: Check if the AI provider is available and authenticated
      operationId: getProviderStatus
      responses:
        '200':
          description: Provider status retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProviderStatusResponse'

components:
  schemas:
    CommandSuggestionRequest:
      type: object
      required:
        - query
        - context
      properties:
        query:
          type: string
          description: User's command description or intent
          example: "list all python files modified in last 24 hours"
          maxLength: 500
        context:
          $ref: '#/components/schemas/ContextInformation'
        preferences:
          $ref: '#/components/schemas/UserPreferences'
        provider_hint:
          type: string
          enum: [openai, anthropic, google, local]
          description: Preferred provider for this request

    CommandSuggestionResponse:
      type: object
      required:
        - command
        - confidence
        - provider
      properties:
        command:
          type: string
          description: Suggested shell command
          example: "find . -name '*.py' -mtime -1"
        explanation:
          type: string
          description: Brief explanation of the command
          example: "Finds Python files modified in the last 24 hours"
        confidence:
          type: number
          format: float
          minimum: 0.0
          maximum: 1.0
          description: Confidence score for the suggestion
        provider:
          type: string
          enum: [openai, anthropic, google, local]
          description: Provider that generated the suggestion
        alternatives:
          type: array
          items:
            type: string
          description: Alternative command suggestions
        safety_level:
          type: string
          enum: [safe, caution, warning]
          description: Safety assessment of the suggested command

    ContextInformation:
      type: object
      properties:
        directory:
          $ref: '#/components/schemas/DirectoryContext'
        git:
          $ref: '#/components/schemas/GitContext'
        environment:
          $ref: '#/components/schemas/EnvironmentContext'
        history:
          $ref: '#/components/schemas/HistoryContext'

    DirectoryContext:
      type: object
      properties:
        current:
          type: string
          description: Current working directory
          example: "/home/user/projects/my-app"
        type:
          type: string
          enum: [git_repo, project, home, system]
          description: Type of directory
        permissions:
          type: array
          items:
            type: string
            enum: [read, write, execute]
        file_count:
          type: integer
          description: Number of files in current directory

    GitContext:
      type: object
      properties:
        repository:
          type: string
          description: Repository name
        branch:
          type: string
          description: Current branch name
        status:
          type: string
          enum: [clean, dirty, ahead, behind, diverged]
        remote:
          type: string
          description: Remote repository URL
        staged_files:
          type: integer
          description: Number of staged files
        unstaged_files:
          type: integer
          description: Number of unstaged files

    EnvironmentContext:
      type: object
      properties:
        shell:
          type: string
          enum: [zsh, bash, fish]
        python_env:
          type: string
          description: Active Python virtual environment
        node_env:
          type: string
          description: Active Node.js version
        docker_context:
          type: string
          description: Active Docker context
        kubernetes_context:
          type: string
          description: Active Kubernetes context

    HistoryContext:
      type: object
      properties:
        recent_commands:
          type: array
          items:
            type: string
          maxItems: 10
          description: Recent command history (sanitized)
        patterns:
          type: array
          items:
            type: string
          description: Identified usage patterns
        frequency:
          type: object
          additionalProperties:
            type: integer
          description: Command frequency map

    UserPreferences:
      type: object
      properties:
        privacy_level:
          type: string
          enum: [strict, balanced, permissive]
          default: balanced
        max_tokens:
          type: integer
          minimum: 50
          maximum: 500
          default: 150
        temperature:
          type: number
          format: float
          minimum: 0.0
          maximum: 1.0
          default: 0.3
        response_timeout:
          type: number
          format: float
          minimum: 0.1
          maximum: 5.0
          default: 0.5

    ProviderStatusResponse:
      type: object
      required:
        - provider
        - available
        - authenticated
      properties:
        provider:
          type: string
          enum: [openai, anthropic, google, local]
        available:
          type: boolean
          description: Whether the provider is available
        authenticated:
          type: boolean
          description: Whether authentication is successful
        method:
          type: string
          enum: [cli, api, none]
          description: Authentication method used
        rate_limit:
          $ref: '#/components/schemas/RateLimitInfo'
        performance:
          $ref: '#/components/schemas/PerformanceInfo'

    RateLimitInfo:
      type: object
      properties:
        requests_remaining:
          type: integer
          description: Remaining requests in current window
        reset_time:
          type: string
          format: date-time
          description: When rate limit resets
        daily_quota:
          type: integer
          description: Daily request quota

    PerformanceInfo:
      type: object
      properties:
        avg_response_time:
          type: number
          format: float
          description: Average response time in seconds
        success_rate:
          type: number
          format: float
          minimum: 0.0
          maximum: 1.0
          description: Success rate percentage
        last_error:
          type: string
          description: Last error message if any

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          enum: [invalid_request, authentication_failed, rate_limited, provider_unavailable, internal_error]
        message:
          type: string
          description: Human-readable error message
        details:
          type: object
          description: Additional error details
        fallback_available:
          type: boolean
          description: Whether local fallback is available
        retry_after:
          type: integer
          description: Seconds to wait before retrying

  securitySchemes:
    CLIAuth:
      type: apiKey
      in: header
      name: CLI-Session
      description: CLI-based authentication token

    APIKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      description: API key authentication

    BearerAuth:
      type: http
      scheme: bearer
      description: Bearer token authentication

security:
  - CLIAuth: []
  - APIKeyAuth: []
  - BearerAuth: []

tags:
  - name: AI Suggestions
    description: AI-powered command suggestions
  - name: Provider Management
    description: Provider status and management
  - name: Performance
    description: Performance monitoring and metrics