# Performance Monitoring Interface Contract
# Feature 002: Advanced Terminal Productivity Suite

openapi: 3.0.3
info:
  title: Performance Monitoring Interface
  description: |
    Interface contract for performance monitoring and constitutional compliance
    tracking in the Advanced Terminal Productivity Suite.
  version: 1.0.0
  contact:
    name: Advanced Terminal Productivity
    url: https://github.com/ghostty-config-files

servers:
  - url: file://~/.config/terminal-ai
    description: Local file-based monitoring interface

paths:
  /metrics/startup:
    post:
      summary: Record shell startup metrics
      description: Record timing and performance data for shell startup
      operationId: recordStartupMetrics
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StartupMetrics'
      responses:
        '200':
          description: Metrics recorded successfully
        '400':
          description: Invalid metrics data

  /metrics/ai-performance:
    post:
      summary: Record AI provider performance
      description: Record performance metrics for AI provider interactions
      operationId: recordAIPerformance
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AIPerformanceMetrics'
      responses:
        '200':
          description: AI performance metrics recorded

  /compliance/constitutional:
    get:
      summary: Get constitutional compliance status
      description: Retrieve current constitutional compliance score and status
      operationId: getConstitutionalCompliance
      responses:
        '200':
          description: Compliance status retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConstitutionalComplianceResponse'

    post:
      summary: Validate constitutional compliance
      description: Perform constitutional compliance validation
      operationId: validateConstitutionalCompliance
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ComplianceValidationRequest'
      responses:
        '200':
          description: Compliance validation completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ComplianceValidationResponse'

  /alerts/performance:
    post:
      summary: Trigger performance alert
      description: Trigger alert when performance thresholds are exceeded
      operationId: triggerPerformanceAlert
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PerformanceAlert'
      responses:
        '200':
          description: Alert triggered successfully

components:
  schemas:
    StartupMetrics:
      type: object
      required:
        - timestamp
        - total_time_ms
      properties:
        timestamp:
          type: string
          format: date-time
          description: When the startup measurement was taken
        total_time_ms:
          type: number
          format: float
          description: Total shell startup time in milliseconds
          maximum: 50.0  # Constitutional requirement
        plugin_load_ms:
          type: number
          format: float
          description: Time to load all plugins
        theme_load_ms:
          type: number
          format: float
          description: Time to load theme
        ai_init_ms:
          type: number
          format: float
          description: Time to initialize AI providers
        memory_usage_mb:
          type: number
          format: float
          description: Memory usage in MB
          maximum: 150.0  # Constitutional requirement
        shell_type:
          type: string
          enum: [zsh, bash, fish]
        session_id:
          type: string
          description: Unique session identifier

    AIPerformanceMetrics:
      type: object
      required:
        - timestamp
        - provider
        - response_time_ms
      properties:
        timestamp:
          type: string
          format: date-time
        provider:
          type: string
          enum: [openai, anthropic, google, local]
        response_time_ms:
          type: number
          format: float
          description: Response time in milliseconds
          maximum: 500.0  # Timeout threshold
        query:
          type: string
          description: Sanitized query (no personal info)
        success:
          type: boolean
          description: Whether the request succeeded
        fallback_used:
          type: boolean
          description: Whether local fallback was used
        cache_hit:
          type: boolean
          description: Whether response came from cache
        tokens_used:
          type: integer
          description: Number of tokens consumed
        error_type:
          type: string
          enum: [timeout, auth_failure, rate_limit, network_error, other]
          description: Error type if request failed

    ConstitutionalComplianceResponse:
      type: object
      required:
        - overall_score
        - foundation_preserved
        - performance_compliant
        - privacy_compliant
      properties:
        overall_score:
          type: number
          format: float
          minimum: 0.0
          maximum: 100.0
          description: Overall compliance score (target ≥99.6%)
        foundation_preserved:
          type: boolean
          description: Whether existing functionality is preserved
        performance_compliant:
          type: boolean
          description: Whether performance targets are met
        privacy_compliant:
          type: boolean
          description: Whether privacy requirements are met
        details:
          $ref: '#/components/schemas/ComplianceDetails'
        last_validated:
          type: string
          format: date-time
        violations:
          type: array
          items:
            $ref: '#/components/schemas/ComplianceViolation'

    ComplianceDetails:
      type: object
      properties:
        foundation_score:
          type: number
          format: float
          description: Foundation preservation score
        performance_score:
          type: number
          format: float
          description: Performance compliance score
        privacy_score:
          type: number
          format: float
          description: Privacy compliance score
        startup_time_avg:
          type: number
          format: float
          description: Average startup time in ms
        memory_usage_avg:
          type: number
          format: float
          description: Average memory usage in MB
        ai_response_time_avg:
          type: number
          format: float
          description: Average AI response time in ms

    ComplianceValidationRequest:
      type: object
      properties:
        validate_foundation:
          type: boolean
          default: true
        validate_performance:
          type: boolean
          default: true
        validate_privacy:
          type: boolean
          default: true
        deep_scan:
          type: boolean
          default: false
          description: Perform comprehensive validation

    ComplianceValidationResponse:
      type: object
      required:
        - validation_id
        - timestamp
        - results
      properties:
        validation_id:
          type: string
          description: Unique validation run identifier
        timestamp:
          type: string
          format: date-time
        results:
          $ref: '#/components/schemas/ConstitutionalComplianceResponse'
        recommendations:
          type: array
          items:
            $ref: '#/components/schemas/ComplianceRecommendation'

    ComplianceViolation:
      type: object
      required:
        - type
        - severity
        - description
      properties:
        type:
          type: string
          enum: [foundation, performance, privacy, security]
        severity:
          type: string
          enum: [critical, warning, info]
        description:
          type: string
          description: Human-readable violation description
        component:
          type: string
          description: Component or feature causing violation
        remediation:
          type: string
          description: Suggested fix for the violation
        impact_score:
          type: number
          format: float
          minimum: 0.0
          maximum: 10.0

    ComplianceRecommendation:
      type: object
      required:
        - priority
        - action
        - expected_improvement
      properties:
        priority:
          type: string
          enum: [high, medium, low]
        action:
          type: string
          description: Recommended action to improve compliance
        expected_improvement:
          type: number
          format: float
          description: Expected compliance score improvement
        effort_estimate:
          type: string
          enum: [low, medium, high]
        component:
          type: string
          description: Component that needs improvement

    PerformanceAlert:
      type: object
      required:
        - alert_type
        - threshold_exceeded
        - current_value
        - timestamp
      properties:
        alert_type:
          type: string
          enum: [startup_time, memory_usage, ai_response_time, compliance_score]
        threshold_exceeded:
          type: number
          format: float
          description: The threshold that was exceeded
        current_value:
          type: number
          format: float
          description: Current measured value
        timestamp:
          type: string
          format: date-time
        severity:
          type: string
          enum: [warning, critical]
        message:
          type: string
          description: Human-readable alert message
        suggested_actions:
          type: array
          items:
            type: string
          description: Suggested actions to resolve the issue
        auto_remediation:
          type: boolean
          description: Whether automatic remediation was attempted

tags:
  - name: Metrics
    description: Performance metrics collection
  - name: Compliance
    description: Constitutional compliance monitoring
  - name: Alerts
    description: Performance and compliance alerting

# Constitutional Compliance Thresholds
x-constitutional-requirements:
  startup_time_max_ms: 50.0
  memory_usage_max_mb: 150.0
  ai_response_timeout_ms: 500.0
  compliance_score_min: 99.6
  foundation_preservation: true
  privacy_protection: true