# Ghostty Configuration Files - GitHub Pages
title: "Ghostty Configuration Files"
description: "Comprehensive terminal environment setup with 2025 optimizations, AI integration, and visual installation guide"
baseurl: "/ghostty-config-files"
url: "https://mister-k.github.io"

# GitHub repository
repository: mister-k/ghostty-config-files
github:
  owner_name: mister-k
  repository_name: ghostty-config-files

# Build settings
theme: jekyll-theme-minimal
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index

# SEO and social
author: mister-k
twitter:
  username: mister-k
social:
  name: mister-k
  links:
    - https://github.com/mister-k

# Content settings
relative_links:
  enabled: true
  collections: true

# Default front matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      author: mister-k

# Collections
collections:
  screenshots:
    output: true
    permalink: /:collection/:name/
  installation_steps:
    output: true
    permalink: /:collection/:name/

# Navigation
navigation:
  - title: "Home"
    url: "/"
  - title: "Installation Guide"
    url: "/installation/"
  - title: "Screenshots Gallery"
    url: "/screenshots/"
  - title: "Configuration"
    url: "/configuration/"
  - title: "GitHub Repository"
    url: "https://github.com/mister-k/ghostty-config-files"

# Include/exclude
include:
  - assets/
  - _pages/

exclude:
  - node_modules/
  - scripts/
  - configs/
  - local-infra/
  - "*.sh"
  - Gemfile
  - Gemfile.lock

# Sass configuration
sass:
  sass_dir: _sass
  style: compressed

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    block:
      line_numbers: true
